### ISSUE TITLE
Duplicate ReconciliationSucceeded events produced by kustomization controller despite no changes

### ISSUE THREAD

**Issue by shailpatels** [fluxcd/kustomize-controller#1280]
It appears that the kustomziation controller is creating an event for each ReconciliationSucceeded triggered by the `interval` despite no changes reported by the kustomization controller itself.

As a result, the notification controller is picking up each event and sending it out which is causing some spam.

Some observations:
From a `kubectl describe kustomization/<my_kustomization> -n <my_namespace>`
```
Normal  ReconciliationSucceeded  59s (x72 over 20h)  kustomize-controller  (combined from similar events): Reconciliation finished in 116.431048ms, next run in 5m0s
```

The `Status.Conditions. Last Transition Time` also updates with each reconcillation

I also see the `Metadata.Resource Version` increment even though the generation and uid for the kustomization stays the same .

However during this time, the kustomziation controller's logs is reporting `{"level":"info","ts":"2024-11-05T16:59:40.336Z","msg":"server-side apply completed" .. ` with no changes 

Manually doing a `flux reconcile kustomization <my_kustomization> -n <my_namespace>` causes an event as well even though there are no changes or diff detected by flux.

Tested on `flux version 2.3.0`
additional context in a slack conversation here: https://cloud-native.slack.com/archives/CLAJ40HV3/p1730772392863339

**Comment by kingdonb** [comment]
I reviewed the details with @shailpatels in the slack thread, I have not gone to the length of configuring my alerts yet to verify the issue from end to end, but I see similar behavior in my minimal test configuration.

I'm using flux-operator, (I don't think that has anything to do with the report) and Flux 2.4.0

It doesn't make sense to me that a dry run with no changes triggers the `lastTransitionTime` to change, creating a new `resourceVersion` - maybe this is intended behavior, but I don't think so, my expectation is there shouldn't be any alerts (events) emitted until the Kustomization is changing something.

The Kustomization API:
* https://github.com/fluxcd/kustomize-controller/blob/main/docs/spec/v1/kustomizations.md#reconciling-kustomization
> The kustomize-controller marks a Kustomization as reconciling when it starts the reconciliation of the same.

doesn't go into detail about it, but it does seem to be expected behavior.

an earlier version:
* https://github.com/fluxcd/kustomize-controller/blob/d7bad03364cf2ab7b7077061b99be2fc4d4c81cb/docs/spec/v1beta2/kustomizations.md#L1423-L1457
seemed to call this out as expected behavior as well:

> Every time the controller starts reconciling a `Kustomization`, it adds the `Reconciling` condition in `status` and
updates its message to report the action performed during a reconciliation run

I don't think this aligns with our expectations about how alerts should work though, so I asked @shailpatels to file this as an issue - I'm going to bring this up at the dev meeting so we can try to get consensus about whether it is a bug or not.

Thanks for the report!

**Comment by kingdonb** [comment]
I didn't notice this because I don't have any actively configured alerts on clusters I'm monitoring now, but I will add some again. In the past I can see I never had any filters configured for `Reconciliation Succeeded` events, only these filters (which may not be relevant anymore)

```
  exclusionList:
    - '^Dependencies do not meet ready condition, retrying in \d+s$'
    - '.*skipped$'
```

I just noticed that each condition has its own lastTransitionTime. So it's the `lastTransitionTime` on the `Ready` status which I did not expect to see moving until an actual dry run detects a diff to apply, I thought that the dry run happens before the event emitted when reconciliation starts.

But that's not what I see in the code:

https://github.com/fluxcd/kustomize-controller/blob/d7bad03364cf2ab7b7077061b99be2fc4d4c81cb/internal/controller/kustomization_controller.go#L294

The first thing that kustomize controller reconcile function does is mark the ready condition unknown (after the artifact revision is successfully fetched.)

I'm surprised we don't see any other reports like this one! Emitting any message as an alert once per interval should have been flagged, I'd like to go back and see if there is a version where this behavior was introduced because I'm sure it didn't work like that before `v1` Kustomization.

The easy fix is to filter `ReconciliationSucceeded` events with an exclusion in the exclusion list, but I think that the workflow @shailpatels is building requires that event, so it can trigger an E2E test downstream. (But only when something changed...)

**Comment by shailpatels** [comment]
> The easy fix is to filter ReconciliationSucceeded events with an exclusion in the exclusion list, but I think that the workflow @shailpatels is building requires that event, so it can trigger an E2E test downstream. (But only when something changed...)

Yeah exactly, unfortunately filtering out that event prevents us from seeing the actual transition from in progress to ready. Also surprised this isn't seen elsewhere, I would think this is a pretty common need to kick off a flux kustomization and want to know when its initially ready through automation.

**Comment by stefanprodan** [comment]
ReconciliationSucceeded events are dropped by notification-controller alerts, and yes this is expected behavior this is required by the commit status updates.

**Comment by shailpatels** [comment]
@stefanprodan 
> ReconciliationSucceeded events are dropped by notification-controller alerts, and yes this is expected behavior this is required by the commit status updates.

I'm not seeing the notification controller drop ReconcilationSucceeded events, I see the following line repeated with ever kubectl reconciliation event

```
{"level":"info","ts":"2024-11-06T14:32:19.401Z","logger":"event-server","msg":"dispatching event","eventInvolvedObject":{"kind":"Kustomization","namespace":"shail-notification-test","name":"my-kustomization","uid":"02350a0b-a8a3-4cd3-bf58-5400c0fc9662","apiVersion":"kustomize.toolkit.fluxcd.io/v1","resourceVersion":"365594"},"message":"Reconciliation finished in 9m30.273030378s, next run in 5m0s"}
```

For commit status updates I think an update whenever the state changes would be enough instead of a continuous stream of updates to avoid unnecessary requests

**Comment by kingdonb** [comment]
Can you clarify what notification provider you are using @shailpatels 

I do not see this alert notification being produced for `ReconciliationSucceeded` in my Slack provider

I was not able to understand from the code how this event is filtered by default, I do see the event in the notification controller logs, but it does not reach my slack channel unless there is some news to report:

<img width="624" alt="Screenshot 2024-11-06 at 10 13 19 AM" src="https://github.com/user-attachments/assets/3e8ca40f-8028-4363-b4c1-491370035e58">

The event is produced on the kubernetes side, received by notification controller, but not escalated by the alert.

(I used this provider, with a legacy slack bot token URL)

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack-bot
  namespace: cozy-fluxcd
spec:
  channel: gitops
  secretRef:
    name: slack-bot-token
  type: slack
```

**Comment by kingdonb** [comment]
I found an earlier report of this issue in the Notification controller repo:
* https://github.com/fluxcd/notification-controller/issues/359

It mentions the generic webhook provider (which I see you are using, going back through our slack thread)

**Comment by shailpatels** [comment]
@kingdonb I'm using the generic webhook provider

```
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: test-webhook
  namespace: shail-notification-test
spec:
  type: generic
  address: http://172.24.207.81:5000/flux-webhook-test
```

**Comment by stefanprodan** [comment]
If you use the generic one, it’s up to you to drop these, there is a dedicated event for when the cluster state changes that includes the list of objects and their change status.

**Comment by shailpatels** [comment]
> If you use the generic one, it’s up to you to drop these, there is a dedicated event for when the cluster state changes that includes the list of objects and their change status.

@stefanprodan oh really? What event is that, based on this doc https://fluxcd.io/flux/components/notification/alerts/#event-sources I don't see anything like that

**Comment by stefanprodan** [comment]
Here https://github.com/fluxcd/kustomize-controller/blob/d7bad03364cf2ab7b7077061b99be2fc4d4c81cb/internal/controller/kustomization_controller.go#L843-L846

**Comment by kingdonb** [comment]
We have explained part of the behavior we're seeing, at least.

In part of the config that wasn't shared, there was an `inclusionList`:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: kustomization-done
  namespace: shail-notification-test
spec:
  summary: "kustomization completed"
  providerRef:
    name: test-webhook
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'my_kustomization'
      namespace: shail-notification-test
  inclusionList:
  - ".*Reconciliation finished.*"
```

We were looking for more information in the events, assuming Kubernetes Events and Flux Alert events are 1:1 but they are not.

I have tested a generic webhook and here's what I see:

```
{..., 'message': 'Deployment/water/water-cmd configured', 'reason': 'Progressing', 'metadata': {'revision': 'main@sha1:766cb0d6d945fe122bceff29ef09a4013082cb81', 'summary': 'test-alert fired'}, 'reportingController': 'kustomize-controller', 'reportingInstance': 'kustomize-controller-69c69c4d7f-lkww7'}
```

The first event, `reason: Progressing` has a `message` that shows what the dry-run is changing. (There's no Kubernetes event for this)

```
{..., 'message': 'Health check passed in 10.174615036s', 'reason': 'Progressing', 'metadata': {'revision': 'main@sha1:766cb0d6d945fe122bceff29ef09a4013082cb81', 'summary': 'test-alert fired'}, 'reportingController': 'kustomize-controller', 'reportingInstance': 'kustomize-controller-69c69c4d7f-lkww7'}
```

^ Next, we get another `reason: Progressing` event that tells us when the Health check passed. (I did not see this until I enabled `wait: true` in my Kustomization, since no health check is performed then) - again, there's no Kubernetes event. But as long as we have an Alert configured which does not exclude this message (or filter by `includeList`) we can monitor for the "Health check passed" message and it tells us what we need to know, time to fire the e2e test.

Finally:

```
{..., 'message': 'Reconciliation finished in 10.717105311s, next run in 10m0s', 'reason': 'ReconciliationSucceeded', 'metadata': {'commit_status': 'update', 'revision': 'main@sha1:766cb0d6d945fe122bceff29ef09a4013082cb81', 'summary': 'test-alert fired'}, 'reportingController': 'kustomize-controller', 'reportingInstance': 'kustomize-controller-69c69c4d7f-lkww7'}
```

At basically the same time as the health check message, a few milliseconds later, I get a `ReconciliationSucceeded` reason. This one also gets emitted as a Kubernetes event, and it happens every interval. And that's intended. Now I get it.

It is a bit counter-intuitive to listen for a `Progressing` event that has some particular message body, but it seems like it would solve @shailpatels' use case here. Thanks for working through this with me, I am glad I understand it better now 🎉

**Comment by kingdonb** [comment]
I believe the mystery is solved, tl;dr: there is a `Health check passed` message with `reason: Progressing` that gets sent at the appropriate time, filtering for that string in the inclusionList works, and `ReconciliationSucceeded` alert can be ignored.

(The health checks are only performed if `healthChecks` or `wait: true` are set, otherwise there is no way to know when the kustomization applied resources are ready.)

**Comment by shailpatels** [comment]
Thanks for your help @kingdonb  for tracking this down!
