### ISSUE TITLE
Support for custom plugins

### ISSUE THREAD

**Issue by slamdev** [fluxcd/kustomize-controller#323]
In docs it says

> --enable_alpha_plugins is disabled by default, so it uses only the built-in plugins.

Any particular reason for it?

Kustomize plugins system is very powerful and a lot of ppl are using it.

Ref to docs:  https://kubectl.docs.kubernetes.io/guides/extending_kustomize/execpluginguidedexample/

**Comment by stefanprodan** [comment]
While executing random binaries on your local machine may be acceptable, inside a container with cluster admin access it becomes a major security concern. There is a PR that enables custom plugins [here](#163), you would have to place the binaries in Git, which I think it's also an issue but it could be somehow better than building your own kustomize-controller container image.

**Comment by slamdev** [comment]
usually you can cover a lot with simple bash scripts that is fine to store in git. for more complex cases a sidecar approach with shared volume can do the job. 

do you have any plans to merge that PR?

**Comment by stefanprodan** [comment]
> usually you can cover a lot with simple bash scripts that is fine to store in git.

There is no bash in kustomize-controller container.

**Comment by slamdev** [comment]
yes, there is no **bash** shell, but there is **sh** :)

**Comment by kopiczko** [comment]
How about plugins unrelated to kustomize? They could be mounted in the pod. This is what Argo CD is doing: https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/

**Comment by stefanprodan** [comment]
> How about plugins unrelated to kustomize? They could be mounted in the pod.

We had that in Flux v1 and it turned out to be a security nightmare. Flux v2 is multi-tenant by design, running arbitrary binaries and scripts inside a container with cluster admin access would break all security boundaries we've put in place. Imagine a tenant has a script that dumps all secrets from all namespaces and posts them to some external URL.

**Comment by kopiczko** [comment]
> Imagine a tenant has a script that dumps all secrets

If you have a tenant you don't trust and they can mount something to a pod with with cluster admin access isn't that already the issue? If this pod has `sh` they can `kubectl exec` anyway. Do I miss something here?

**Comment by stefanprodan** [comment]
>  Do I miss something here?

Yes, check out https://github.com/fluxcd/flux2-multi-tenancy a tenant can't exec into flux control plane nor can it run pods under cluster admin, but with a plugin they could elevate to admin.

**Comment by kopiczko** [comment]
So if the plugin was configured on the controller level (and IIUC the tenant doesn't have access to it) and only referenced from the CR, would that be ok security-wise?

**Comment by kopiczko** [comment]
@stefanprodan how about something like a empty-canvas-controller which would be designed to be configured with a user mounted binary/plugin? That binary/plugin should be generating manifests based on the tarball URL or path to unpacked repository files.

**Comment by khrisrichardson** [comment]
Here's a gist with my [kustomize-controller Dockerfile](https://gist.github.com/khrisrichardson/0e65bd08b6c9c56df96b02fcfa535b8a#file-dockerfile), [flux2 kustomization.yaml](https://gist.github.com/khrisrichardson/0e65bd08b6c9c56df96b02fcfa535b8a#file-kustomization-yaml) and [flux2 gotk-patchs.yaml](https://gist.github.com/khrisrichardson/0e65bd08b6c9c56df96b02fcfa535b8a#file-gotk-patches-yaml) files to enable KRM config function functionality, in case anyone finds it useful. The build arguments to the Dockerfile are furnished externally, and at the time of this comment are set to:

```yaml
DOCKER_IO_ALPINE_HELM: 3.6.3
DOCKER_IO_GOLANG: 1.17.0-alpine3.14
GHCR_IO_FLUXCD_KUSTOMIZE_CONTROLLER: v0.14.0
GITHUB_COM_FLUXCD_KUSTOMIZE_CONTROLLER: v0.14.0
PKGS_ALPINELINUX_ORG_PACKAGE_V3_14_COMMUNITY_DOCKER_CLI: 20.10.7-r1
PKGS_ALPINELINUX_ORG_PACKAGE_V3_14_MAIN_GIT: 2.32.0-r0
```

**Comment by kingdonb** [comment]
I think it's clear enough at this point that Flux will not change its position on support for outside binaries; if we want to add more features to Kustomize controller, they need to be available as go packages so that we can reference their logic without shelling out to a third-party. It's not the third-parties we distrust, it's the shelling out that's the dangerous part.

Closing, as this issue appears inactive and is unlikely to progress any further.

**Comment by ringerc** [comment]
This is a big challenge for users of very widely deployed systems like SOPS and kustomize-sops for secrets management.

**Comment by stefanprodan** [comment]
@ringerc Flux has native support for SOPS, please see the docs: https://fluxcd.io/docs/components/kustomize/kustomization/#secrets-decryption

**Comment by keskad** [comment]
I think its thinking of Flux users like idiots. People should know what plugins are they using and carefully decide themselves - and take the consequences. Best way there is to add a warning in the docs in my opinion :sunglasses: 

For example I had to write a Kustomize plugin to migrate a specific project into ArgoCD, I would not be able to do the same thing with the FluxCD :wink:

**Comment by kingdonb** [comment]
No offense to any users intended but, if you treat the user like they are stupid when designing software, you are usually not disappointed. This decision constrains the users short-term choices somewhat in exchange for a great deal of predictability and stability within the ecosystem where we can say Flux only incorporates declarative primitives and works entirely within the Kubernetes API. You can still integrate third-party tooling with CI or custom operators. Flux v1 allowed certain types of shelling out for users, and it was fraught. The risk of compromise is significant, and easily mitigated by this design decision.

**Comment by khrisrichardson** [comment]
@keskad and @kingdonb I'm not sure if it has come to your attention that [OCI repository](https://fluxcd.io/docs/components/source/ocirepositories/) support was recently added. It relegates the responsibility of manifest hydration to your CI tool, allowing the CD tool to be agnostic to the inordinate combination of rendering tools that one has at their disposal. Seems a reasonable tradeoff IMHO.

**Comment by gberche-orange** [comment]
A common use-case for kustomize plugins is the reuse of off-the-shelf yaml/json asserts to construct K8S resources (typically grafana dashboards or [prometheus rules](https://github.com/samber/awesome-prometheus-alerts/blob/master/dist/rules/host-and-hardware/node-exporter.yml). 

I understand from https://github.com/kubernetes-sigs/kustomize/issues/4636 that this is not in scope for future Kustomize builtin support, and could only be supported by a custom transformer, typically a custom generator.

Major drawbacks of custom resources controllers (see https://github.com/prometheus-operator/prometheus-operator/issues/4495#issuecomment-1251026056) loading reusable yaml/json fragments from a ConfigMap (or Secret generated from Kustomize builtin generators) are:
* the CR maintainers can't leverage CRD schema to perform input validation on the ConfigMap. Therefore, feedback on syntax errors on the ConfigMap content gets delayed later in the deployment workflow and most costly to diagnose/fix.
* transformations to be brought to the reusable yaml/json assets can't be performed by authors using Kustomize patches. 

> You can still integrate third-party tooling with CI or custom operators.

My return on experience from these workarounds:
* A preprocessing CI pipeline performing source templating and rendered K8S spec files into the source git repo, then deployed using Kustomize controller:
   *  While this provides authoring flexibility, this increases length of feedback cycles, adds complexity to the overall authoring workflow.
* A distinct operator supporting native yaml/json templating: [carvel kapp controller](https://carvel.dev/kapp-controller/docs/develop/) with its builtin [ytt yaml templating syntax](https://carvel.dev/ytt/): 
   * This comes with higher syntaxic authoring complexity which makes it hard/challenging to generalize and replace current use-cases satisfied by fluxcd kustomize controller.
   * A functional overlap between fluxcd and carvel kapp controller are causing operational challenges:
      * duplicated tooling for listing/inspecting/pausing/resuming reconciliations 
      * distinct assets inventories
      * duplicated maintenance of source controller configurations: between [flux source controller](https://fluxcd.io/flux/components/source/) and [kapp fetch spec](https://carvel.dev/kapp-controller/docs/develop/app-overview/#specfetch)
      * required operational knowledge to support/troubleshoot both stack
   * A functional overlap between fluxcd and carvel kapp controller are causing *authoring* challenges:
      * Even when encapsulating complex ytt yaml templating in libraries, the basic syntax for deploying resources is distinct between KustomizeController and KappController, surfacing two distinct syntaxes to authors
   * Integration between the two controllers is challenging, e.g.:
      *  Given a Kustomization includes a Kapp CR resource performing ytt yaml rendering of K8S resources (say a PrometheusRule from a [remote url](https://github.com/samber/awesome-prometheus-alerts/blob/master/dist/rules/host-and-hardware/node-exporter.yml))
      * When pausing the Kustomization
      * The Kapp CR resource don't get paused
      
> I'm not sure if it has come to your attention that [OCI repository](https://fluxcd.io/docs/components/source/ocirepositories/) support was recently added. It relegates the responsibility of manifest hydration to your CI tool, allowing the CD tool to be agnostic to the inordinate combination of rendering tools that one has at their disposal. Seems a reasonable tradeoff IMHO.

The workflow detailed in https://github.com/fluxcd/kustomize-controller/pull/163#issuecomment-1162032488  seems similar to the preprocessing CI pipeline approach above, with the following benefits and challenges:
* same authoring Kustomize syntax is used between preprocessing CI step and Flux-based CD steps
* community shares Kustomize plugins for common use-cases instead of custom homemade preprocessing pipelines
* additional challenges of traceability of changes across CI and CD (need detailed metadata in the OCI image produced by CI to track the authored changes to K8S clusters).

**Comment by maulerjan** [comment]
> No offense to any users intended but, if you treat the user like they are stupid when designing software, you are usually not disappointed. This decision constrains the users short-term choices somewhat in exchange for a great deal of predictability and stability within the ecosystem ...

If the creators of operating systems were thinking like this, they would get nowhere and using computers today would be very unpleasant.
