### ISSUE TITLE
anchoring stopped working

### ISSUE THREAD

**Issue by davidkarlsen** [fluxcd/kustomize-controller#369]
I had to:
```
 apiVersion: sources.knative.dev/v1beta1
 kind: ContainerSource
 metadata:
-  name: &srcname awssqs-source
+  name: awssqs-source
   namespace: devops
 spec:
   template:
@@ -24,7 +24,7 @@ spec:
 
         # Knative system variables
         - name: NAME
-          value: *srcname
+          value: awssqs-source
         - name: NAMESPACE
           valueFrom:
             fieldRef:
```
when upgrading from v0.14.2 to v0.15.0, ie upgrading kustomize-controller:
```
-        image: ghcr.io/fluxcd/kustomize-controller:v0.12.2
+        image: ghcr.io/fluxcd/kustomize-controller:v0.13.0
```

**Comment by hiddeco** [comment]
See: https://github.com/fluxcd/kustomize-controller/pull/367

**Comment by sa-spag** [comment]
There's a workaround that was suggested on https://github.com/kubernetes-sigs/kustomize/issues/3675#issuecomment-850442262. It basically introduces a plugin that resolves anchors and aliases beforehand using `yq`. Since plugins are not supported yet (https://github.com/fluxcd/kustomize-controller/issues/120), it's not trivially possible to deploy the workaround. Depending on how likely it is for the upstream issue to be fixed in the near future, could we consider embedding such plugin in the kustomize-controller controller?
