### ISSUE TITLE
Allow hyphen in variable substitution names

### ISSUE THREAD

**Issue by varac** [fluxcd/kustomize-controller#395]
from https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution:

> Note that the name of a variable can contain only alphanumeric and underscore characters. The controller validates the var names using this regular expression: ^[_[:alpha:]][_[:alpha:][:digit:]]*$.

Many charts have variables containing a hyphen (`-`) which cannot get substituted from a Secrect. An example is the bitnami mongodb helm chart, where you can store auth credentials in a Secret (see https://github.com/bitnami/charts/tree/master/bitnami/mongodb#mongodb-parameters):

```
auth.existingSecret | Existing secret with MongoDB® credentials (keys: mongodb-password, mongodb-root-password,  mongodb-replica-set-key)
```
It would be great to allow hyphens in variable substitution names so I can use existing charts without proposing possibly breaking changes by renaming variables.

**Comment by kingdonb** [comment]
Those are not variables, they are YAML keys. The semantics of a Bash string replacement function do not permit dashes in the variable name because Bash does not permit it either.

You can substituteFrom a YAML key of your choice, the substituteFrom examples already show how you can use YAML values with dashes or hyphens present in the string key.

Please check this API doc which covers substitute and substituteFrom:

https://fluxcd.io/docs/components/kustomize/api/#kustomize.toolkit.fluxcd.io/v1beta1.PostBuild

> SubstituteFrom holds references to ConfigMaps and Secrets containing the variables and their values to be substituted in the YAML manifests. The ConfigMap and the Secret data keys represent the var names and they must match the vars declared in the manifests for the substitution to happen.

Does this perhaps satisfy your use case? I realize it is not quite the same use as `substitute`.

The MongoDB helm chart would be applied with a HelmRelease, through Helm Controller, and I think the corresponding features there are a bit more powerful yet:

https://fluxcd.io/docs/components/helm/helmreleases/#values-overrides

https://fluxcd.io/docs/components/helm/helmreleases/#post-renderers

Hopefully one of these options will help!

**Comment by xeruf** [comment]
substituteFrom works, but we had hoped to use the proper existingSecret configuration so the passwords aren't embedded in the ConfigMap:
https://open.greenhost.net/stackspin/stackspin/-/blob/main/flux2/apps/wekan/wekan-values-configmap.yaml#L104

**Comment by kingdonb** [comment]
I don't understand how this is an issue for kustomize-controller.

The config you listed is a values.yaml – I assume the configmap is created in the cluster by kustomize-controller, but the name references can be included directly as strings, without using Kustomize controller's variable substitution feature. You are just passing a string name reference to Helm Controller through the values.yaml, and Helm will use it like any other string name reference. It doesn't have to be a variable substitution via Kustomize, unless there is something I am missing?

The dashes can be part of the value. They cannot be part of the variable name, because they are not compatible with bash substitution. But at no point are configmap names or secret names expected to equate directly with the variable names used to ship string values around.
