### ISSUE TITLE
Wait for Kubernetes Jobs to complete

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/kustomize-controller#553]
Currently kstatus does not support [waiting for jobs](https://github.com/kubernetes-sigs/cli-utils/issues/350) and it doesn't look like this feature will be implemented any time soon. For Flux users this means they can't use the `spec.wait` and `spec.dependsOn` to create a delivery pipeline that applies db migrations (jobs), waits for the migration to complete, and only then apply the application updates.

We should look into kstatus custom status readers (available in cli-utils v0.27.0) and implement our own Job status assertion.

**Comment by gecube** [comment]
I'd like to see this feature switchable, because in some cases you need to wait for jobs, in other cases - it is strongly disadvantage. Also I'd like to mention that in our cases migration are well handled with initContainers inside of micro service deployment (of course, with some kind of foolproof guards - for instance, locks on DB to disable simultaneous run of migration) or with Helm package itself...

**Comment by stefanprodan** [comment]
@gecube you can pick what thighs you want to health check, docs here: https://fluxcd.io/docs/components/kustomize/kustomization/#health-assessment
