### ISSUE TITLE
Flux v2 is much slower than Flux v1?

### ISSUE THREAD

**Issue by nitharsandvag** [fluxcd/kustomize-controller#764]
Hello,

Since we migrated one of our Aks clusters to Flux V2 with the Aks extension, we now notice that the apply times of the yaml's are much slower than with Flux v1.
Compared to the other clusters with Flux v1, it takes about 6 minutes longer to deploy new commits to the cluster.
Sync Interval is set to one minute in the Flux and Kustomize controller.
It looks like the Kustomize Controller goes through all resources with every commit and then deploys the new commits on top, so it always takes so long, is it correct? We have around 3k resources in the git repo (just grepped the "kind:" in the yaml's)
In the log we also see that once reconcilation takes longer than 5 minutes.
Is the new flux with kustomize designed this way or is there something we can do to make the commits applied faster in the cluster like v1?

Thanks

**Comment by kingdonb** [comment]
In the Flux v1 model, applies are completely asynchronous and not atomic at all. So when Flux v1 applies a change, it basically runs `kubectl apply -f` and it is fire-and-forget. Any errors will be reflected in the logs, but they are not blocking the other resources in the commit from applying.

This lack of atomicity is strongly undesirable and changing that was a design goal in Flux v2, which now uses the server-side apply and is implicitly validating the entire apply as a unit.

Applying 3000 resources as an atomic operation is also very expensive for the Kubernetes API, it's expected that this is slow. Longer than 5 minutes seems pretty high, but that is a lot of resources. If you have `spec.wait` enabled, then this does not seem very high anymore – some services with complex inter-dependencies may take that long to become ready.

Flux can use `wait` or non-`wait` mode, can you clarify which mode you are using? (It is a parameter in the `Kustomization` resource.)

Generally my advice would be, do not apply 3000 resources in a single unit. They should be broken up by environment or by service, or by some other logical designation. This will make the server-side apply much faster. It is the coordination which slows down this op, in the Kubernetes API server.

There is also the Flux cheat sheet for performance tuning, which could help (if you have already done this splitting up of resources, then Flux's default concurrency limits may be set too low for that many resources):

https://fluxcd.io/flux/cheatsheets/bootstrap/#increase-the-number-of-workers

So you can increase the number of workers that Flux uses to apply Kustomizations concurrently.

Please let us know if this helps!

**Comment by stefanprodan** [comment]
Flux v1 didn't had wait, it just applied all things and didn't care about it. Saying that v2 is slower while you've told it to wait for 3K objects it's unfair IMO...

**Comment by stefanprodan** [comment]
@nitharsandvag I recommend you take a look at the [example repo](https://github.com/fluxcd/flux2-kustomize-helm-example) and reorganise your repo so that those 3K objects are split intro logical groups (infra, config, apps, etc), this will not only speed up the reconciliation but will also help dealing with incidents, observability, notifications, etc.

**Comment by nitharsandvag** [comment]
Thanks for the quick update, we will check it and make the adjustment accordingly.

**Comment by nitharsandvag** [comment]
@stefanprodan The patch just add few start args and increase cpu and ram to the deployments right? I have just patched manually, should do the same. Lets see if we get some improvements.

- --concurrent=20
- --kube-api-qps=500
- --kube-api-burst=1000
- --requeue-dependency=5s

resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 64Mi

**Comment by kingdonb** [comment]
> I would like to try the increase the number of workers, in the sample they include gotk-components.yaml and gotk-sync.yaml, we don't have those yaml files.
> We have installed flux with the aks extensions with az commands, how can we patch it

If you have installed Flux with the AKS extension, then Flux is installed via helm from outside of Git. There is no manifest in the git repository or place to patch. You can ask AKS/Microsoft support if they have a way designed to customize Flux from outside, but I don't think it's in their design.

Of course you can just overwrite the deployment as it sounds like you must have done, which should be effective until the next version of Flux is released, since it is a Helm upgrade it will put back the arguments how the manifest templates write them in the AKS extension installer (then you have to do it again, update in place?)

Ideally there is a better way, but for AKS Microsoft.flux, I don't know the answer for sure.

**Comment by floriankoch** [comment]
@kingdonb  i am in the same Team as @nitharsandvag , yes we have support - and  i will talk with the AKS folks about this
